/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const find_Logic = require('./code/find-logic');
const hire_Logic = require('./code/hire-logic');
const employee_Logic = require('./code/employee-logic');

class AppWithLogicService extends LCAPApplicationService {
    async init() {

        this.before('find', async (request) => {
            await find_Logic(request);
        });

        this.after('hire', async (results, request) => {
            await hire_Logic(results, request);
        });

        this.on('beOnboard', 'Employee', async (request, next) => {
            await employee_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    AppWithLogicService
};